package com.softdesign.devintensive.utils;

import android.content.IntentSender;

/**
 * Created by Ugluk on 24.06.2016.
 */
public interface ConstantManager {
    String TAG_PREFIX = "DEV ";
    String EDIT_MODE_KEY = "EDIT_MODE_KEY";

    String USER_PHONE_KEY = "USER_KEY_PHONE";
    String USER_MAIL_KEY = "USER_KEY_MAIL";
    String USER_VK_KEY = "USER_KEY_VK";
    String USER_GIT_KEY = "USER_KEY_GIT";
    String USER_BIO_KEY = "USER_KEY_BIO";
    String USER_PHOTO_KEY = "USER_PHOTO_KEY";

    String USER_ID_KEY = "USER_ID_KEY";
    String AUTH_TOKEN_KEY = "AUTH_TOKEN_KEY";

    String USER_RATING_VALUE = "USER_RATING_VALUE";
    String USER_CODE_LINES_VALUE = "USER_CODE_LINES_VALUE";
    String USER_PROJECT_VALUE = "USER_PROJECT_VALUE";

    String FIELD_PHONE_VALUES = "FIELD_PHONE_VALUES";
    String FIELD_EMAIL_VALUES = "FIELD_EMAIL_VALUES";
    String FIELD_GIT_VALUES = "FIELD_GIT_VALUES";
    String FIELD_VK_VALUES = "FIELD_VK_VALUES";
    String FIELD_BIO_VALUES = "FIELD_BIO_VALUES";

    String MAIN_FIRST_NAME_VALUES = "MAIN_FIRST_NAME_VALUES";
    String MAIN_SECOND_NAME_VALUES = "MAIN_SECOND_NAME_VALUES";
    String MAIN_AVATAR_VALUES = "MAIN_AVATAR_VALUES";


    int LOAD_PROFILE_PHOTO = 1;
    int REQUEST_CAMERA_PICTURE = 99;
    int REQUEST_GALLERY_PICTURE = 88;

    int PERMISSION_REQUEST_SETTINGS_CODE = 101;
    int CAMERA_REQUEST_PERMISSION_CODE = 102;
    int CALL_PHONE_REQUEST_PERMISSIONS_CODE = 103;
}